[package]
name = "intra-pipe"
version = "0.1.4"
authors = ["PZ Read"]
edition = "2018"

license = "MIT"
description = "Synchronous/Asynchronous intra-process pipe"
repository = "https://github.com/pzread/intra-pipe-rs"

[dependencies]
futures = "0.1"
tokio-io = "0.1"
tokio-current-thread = "0.1"
